### ISSUE TITLE
Change trigger for metafacture twitter events

### ISSUE THREAD

**Issue by TobiasNx** [hbz/events#6]
At the moment Metafactures Twitter is tweeting when almost all things happen in the repo. Especially with every comment.

We talked about this, that we want to reduce the triggers of the tweets.
I suggest:
- New issue
- New PR
- Closed PR
- New release
- New blogpost
- New fork(?)

**Comment by fsteeg** [comment]
Currently two events trigger tweets: new issues and new comments. I've disabled the tweeting of new comments on our server, so only new issues should be tweeted now. Other triggers would require additional implementation and testing (in what format to tweet exactly etc.). Since I have not worked with the Twitter API since implementing this, it would probably take some time. Maybe with the reduced automatic tweeting (plus some manual tweets for specific things like releases or blog posts) this is enough for now?

**Comment by TobiasNx** [comment]
+1
